clear all;

load ./mat/analyzed_data.mat;

file_id = fopen('mouse_data.csv','w');
label_str = ['oadc,start date,end date,N sessions,mean(rho),std(rho),N moves tot,N moves I,N moves II,' ...
             'median(Delta),iqr(Delta),median(Delta I),iqr(Delta I),median(Delta II),iqr(Delta II),' ...
             'median(D),iqr(D),median(D I),iqr(D I),median(D II),iqr(D II),' ...
             'median(K),iqr(K),median(K I),iqr(K I),median(K II),iqr(K II),' ...
             'median(T),iqr(T),median(T I),iqr(T I),median(T II),iqr(T II),' ...
             'a tilde,b,a tilde I,b I,a tilde II,b II,' ...
             'mean(tauM),std(TauM),mean(tauM I),std(tauM I),mean(tauM II),std(tauM II),' ...
             'median(idle),iqr(idle)' ];
fprintf(file_id,'%s\n',label_str);
for i = 1:length(analyzed_data);
    for j = 1:length(analyzed_data{i})
        line_str = [ '%d,%s,%s,%d,%f,%f,%d,%d,%d,%f,%f,%f,%f,%f,%f,%f,' ...
                     '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
                     '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f' ];
        fprintf(file_id,[line_str,'\n'], ...
                analyzed_data{i}{j}.oadc, ...
                datestr(analyzed_data{i}{j}.dates(1)), ...
                datestr(analyzed_data{i}{j}.dates(2)-1), ...
                analyzed_data{i}{j}.num_sessions, ...
                analyzed_data{i}{j}.rho(1), ...
                analyzed_data{i}{j}.rho(2), ...
                analyzed_data{i}{j}.num_moves, ...
                analyzed_data{i}{j}.num_moves_I, ...
                analyzed_data{i}{j}.num_moves_II, ...
                analyzed_data{i}{j}.Delta(1), ...
                analyzed_data{i}{j}.Delta(2), ...
                analyzed_data{i}{j}.Delta_I(1), ...
                analyzed_data{i}{j}.Delta_I(2), ...
                analyzed_data{i}{j}.Delta_II(1), ...
                analyzed_data{i}{j}.Delta_II(2), ...
                analyzed_data{i}{j}.D(1), ...
                analyzed_data{i}{j}.D(2), ...
                analyzed_data{i}{j}.D_I(1), ...
                analyzed_data{i}{j}.D_I(2), ...
                analyzed_data{i}{j}.D_II(1), ...
                analyzed_data{i}{j}.D_II(2), ...
                analyzed_data{i}{j}.K(1), ...
                analyzed_data{i}{j}.K(2), ...
                analyzed_data{i}{j}.K_I(1), ...
                analyzed_data{i}{j}.K_I(2), ...
                analyzed_data{i}{j}.K_II(1), ...
                analyzed_data{i}{j}.K_II(2), ...
                analyzed_data{i}{j}.T(1), ...
                analyzed_data{i}{j}.T(2), ...
                analyzed_data{i}{j}.T_I(1), ...
                analyzed_data{i}{j}.T_I(2), ...
                analyzed_data{i}{j}.T_II(1), ...
                analyzed_data{i}{j}.T_II(2), ...
                analyzed_data{i}{j}.B(1), ...
                analyzed_data{i}{j}.B(2), ...
                analyzed_data{i}{j}.B_I(1), ...
                analyzed_data{i}{j}.B_I(2), ...
                analyzed_data{i}{j}.B_II(1), ...
                analyzed_data{i}{j}.B_II(2), ...
                analyzed_data{i}{j}.Tau(1), ...
                analyzed_data{i}{j}.Tau(2), ...
                analyzed_data{i}{j}.Tau_I(1), ...
                analyzed_data{i}{j}.Tau_I(2), ...
                analyzed_data{i}{j}.Tau_II(1), ...
                analyzed_data{i}{j}.Tau_II(2),...
                analyzed_data{i}{j}.idle_time(1), ...
                analyzed_data{i}{j}.idle_time(2));   
    end
end
fclose(file_id);